# Generated by Django 5.2.17 on 2026-09-25 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('url', models.TextField()),
                ('params_json', models.JSONField(blank=True, default=dict)),
                ('headers_json', models.JSONField(blank=True, default=dict)),
                ('body_json', models.TextField(blank=True, default='')),
                ('auth_type', models.CharField(choices=[('none', 'No Authentication'), ('bearer', 'Bearer Token'), ('api_key', 'API Key'), ('basic', 'Basic Authentication')], default='none', max_length=20)),
                ('auth_config_json', models.JSONField(blank=True, default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, default='', max_length=50)),
                ('error_message', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Request history entries',
                'ordering': ('-executed_at',),
            },
        ),
        migrations.CreateModel(
            name='SavedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('url', models.TextField()),
                ('params_json', models.JSONField(blank=True, default=dict)),
                ('headers_json', models.JSONField(blank=True, default=dict)),
                ('body_json', models.TextField(blank=True, default='')),
                ('auth_type', models.CharField(choices=[('none', 'No Authentication'), ('bearer', 'Bearer Token'), ('api_key', 'API Key'), ('basic', 'Basic Authentication')], default='none', max_length=20)),
                ('auth_config_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_requests', to='core.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', '-updated_at'], name='core_collec_user_id_b49874_idx'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_collection_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='requesthistory',
            index=models.Index(fields=['user', '-executed_at'], name='core_reques_user_id_3ecfb3_idx'),
        ),
        migrations.AddIndex(
            model_name='savedrequest',
            index=models.Index(fields=['user', '-updated_at'], name='core_savedr_user_id_36e82a_idx'),
        ),
        migrations.AddIndex(
            model_name='savedrequest',
            index=models.Index(fields=['user', 'collection', '-updated_at'], name='core_savedr_user_id_8cd45a_idx'),
        ),
    ]
