# Generated by Django 5.2.17 on 2026-10-02 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('value', models.TextField(blank=True, default='')),
                ('is_secret', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_collection_name_per_user',
        ),
        migrations.AddField(
            model_name='collection',
            name='clerk_user_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='clerk_user_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='response_headers_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='response_size_bytes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='savedrequest',
            name='clerk_user_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='auth_type',
            field=models.CharField(choices=[('none', 'No Authentication'), ('bearer', 'Bearer Token'), ('api_key', 'API Key'), ('basic', 'Basic Authentication'), ('oauth2', 'OAuth 2.0')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedrequest',
            name='auth_type',
            field=models.CharField(choices=[('none', 'No Authentication'), ('bearer', 'Bearer Token'), ('api_key', 'API Key'), ('basic', 'Basic Authentication'), ('oauth2', 'OAuth 2.0')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='savedrequest',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10),
        ),
        migrations.AlterField(
            model_name='savedrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['clerk_user_id', '-updated_at'], name='core_collec_clerk_u_fca725_idx'),
        ),
        migrations.AddIndex(
            model_name='requesthistory',
            index=models.Index(fields=['clerk_user_id', '-executed_at'], name='core_reques_clerk_u_19fcfa_idx'),
        ),
        migrations.AddIndex(
            model_name='savedrequest',
            index=models.Index(fields=['clerk_user_id', '-updated_at'], name='core_savedr_clerk_u_fd88fb_idx'),
        ),
        migrations.AddIndex(
            model_name='savedrequest',
            index=models.Index(fields=['clerk_user_id', 'collection', '-updated_at'], name='core_savedr_clerk_u_69aef2_idx'),
        ),
        migrations.AddField(
            model_name='environment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='environmentvariable',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='core.environment'),
        ),
        migrations.AddIndex(
            model_name='environment',
            index=models.Index(fields=['clerk_user_id', '-updated_at'], name='core_enviro_clerk_u_6868c6_idx'),
        ),
        migrations.AddIndex(
            model_name='environment',
            index=models.Index(fields=['user', '-updated_at'], name='core_enviro_user_id_3612d8_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentvariable',
            index=models.Index(fields=['environment', 'key'], name='core_enviro_environ_c8c642_idx'),
        ),
        migrations.AddConstraint(
            model_name='environmentvariable',
            constraint=models.UniqueConstraint(fields=('environment', 'key'), name='unique_var_key_per_env'),
        ),
    ]
